// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzjzcvcyneufijjpzbdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6anpjdmN5bmV1ZmlqanB6YmRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3MjA5NDQsImV4cCI6MjA3OTI5Njk0NH0.878YVMQMOjttMoKeIwaubU8ory0eUeaelEtmZdehX-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);